apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: html-daemonset
spec:
  selector:
    matchLabels:
      name: html-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: html-ds
    spec:
      runtimeClassName: nvidia
      containers:
        - name: html-container  # 添加了容器名称
          image: 10.100.1.1.:5000/mineru:2.6.4
          imagePullPolicy: Always
          command: [ "python3", "/data/MinerU-HTML/houdu/main/main.py" ]
          env:
            - name: PYTHONUNBUFFERED  # 确保Python输出无缓冲
              value: "1"
            - name: GPU_IDS
              value: "0,1,2,3,4,5,6,7"
            - name: VRAM_SIZE_GB
              value: "16"
            - name: WORKERS_PER_GPU
              value: "2"
            - name: GPU_MEMORY_UTILIZATION
              value: "0.45"
            - name: PROPORTION
              value: "0.03"
            - name: TORCHDYNAMO_VERBOSE
              value: "1"
            - name: OMP_NUM_THREADS
              value: "3"
            - name: MKL_NUM_THREADS
              value: "3"
            - name: OPENBLAS_NUM_THREADS
              value: "3"
          resources:
            limits:
              nvidia.com/gpu: 8
              memory: "480Gi"
              cpu: "80"
            requests:
              nvidia.com/gpu: 8
              memory: "480Gi"
              cpu: "80"
          volumeMounts:
            - name: scripts
              mountPath: /data/MinerU-HTML
            - name: mnt
              mountPath: /mnt
          securityContext:
            privileged: true
      volumes:
        - name: scripts
          hostPath:
            path: /data/MinerU-HTML
        - name: mnt
          hostPath:
            path: /ssd/cc-html
            type: DirectoryOrCreate
      nodeSelector:
        accelerator: nvidia-gpu
